### ISSUE TITLE
wrong snefru hash ! 

### ISSUE THREAD

**Issue by RB61** [C0MM4ND/go-snefru#1]
The following test gave me the wrong answer :

package main
 
import (
    "fmt"
    "github.com/go-snefru"
)
 
func main() {
    msg := []byte("hello")
    h := snefru.NewSnefru256(8)
    h.Write(msg) 
    fmt.Printf("%x\n", h.Sum(nil))
}

I got: 
e48fdbb87166fccad8588ab6ff2f5d6d3726b9e395f49f9e7befed7f469c636b

instead of:
7c5f22b1a92d9470efea37ec6ed00b2357a4ce3c41aa6e28e3b84057465dbb56 

the given hash_test.go fails.

**Comment by c0mm4nd** [comment]
fixed on https://github.com/C0MM4ND/go-snefru/commit/87ad2a83afd9e338ce97afdb7776f25e530cd993
